# Generated by Django 3.2 on 2021-06-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=10)),
                ('grade', models.IntegerField()),
                ('school', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '학생 관리',
            },
        ),
    ]
